"""create video_uploads table

Revision ID: 7eade38fd766
Revises: 70e507e0b2b1
Create Date: 2026-09-14 08:40:33.557016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eade38fd766'
down_revision: Union[str, Sequence[str], None] = '70e507e0b2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('total_size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'total_size')
    # ### end Alembic commands ###
